from .video import *
from .discussion import *
from .problem import *
from .status import *
from .exam import *
from .course import *
from .student import *
from .data import *
from .difficulty import *
from .config import *
from .prediction import *
from .detail import *
from .permission import *
