from .video import *
from .discussion import *
from .problem import *
from .status import *
from .exam import *
from .course import *
from .student import *
from .data import *
from .difficulty import *
from .config import *
from .prediction import *
from .detail import *
from .table import *
from .permission import *
from .elective_course import *
from .education import *
from .problem_focus import *
from .mobile_web_video import *
from .newcloud_grade import *
from .open_times import *
from .newcloud_academic import *
from .mobile_classmate import *
from .newcloud_wechat import *
